durunubi:
  api:
    base-url: ${DURUNUBI_API_BASE_URL:https://apis.data.go.kr/B551011/Durunubi}
    service-key: ${DURUNUBI_API_SERVICE_KEY:}
    num-of-rows: ${DURUNUBI_API_NUM_OF_ROWS:1000}

  spring:
    http:
      clients:
        connect-timeout: 5s
        read-timeout: 5s
#http://apis.data.go.kr/B551011/Durunubi/courseList?serviceKey=서비스인증키&pageNo=1&numOfRows=10&MobileOS=ETC&MobileApp=AppTest&crsKorNm=밀양강&crsLevel=2&brdDiv= DNBW