spring:
  config:
    import: "optional:file:.env.local[.properties]" # local에서만 사용
  application:
    name: runpassport-api
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate   # update/create 절대 금지
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    show-sql: false